pipeline:
  name: Build
  identifier: Build
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1704192628541
        repoName: anujrajkumar/Tx-Automate
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: dependencies
                  identifier: dependencies
                  spec:
                    shell: Sh
                    command: |-
                      # java --version
                      #                       # # msbuild --version
                      #                       # # export PATH="$PATH:/root/.dotnet/tools"
                      #                       # # export SONAR_SCANNER_OPTS="-Xmx4096m"
                      #                       # sudo apt update
                      #                       # sudo apt install openjdk-17-jdk
                      #                       # sudo update-alternatives --config java
                      #                       # export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                      #                       # export PATH="$PATH:$JAVA_HOME/bin"
                      #                       # java --version
                      #                       # Update package list
                      #                       sudo apt-get update

                      #                       # Install OpenJDK 17
                      #                       sudo apt-get install -y openjdk-17-jdk

                      #                       # Add OpenJDK 17 to alternatives
                      #                       sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
                      #                       sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1
                      #                       sudo update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/java-17-openjdk-amd64/bin/jar 1

                      #                       # Set OpenJDK 17 as the default
                      #                       sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
                      #                       sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
                      #                       sudo update-alternatives --set jar /usr/lib/jvm/java-17-openjdk-amd64/bin/jar

                      #                       # Verify the Java version
                      #                       export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                      #                       export PATH="$PATH:$JAVA_HOME/bin"
                      java --version
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: |-
                      # java --version
                      # # msbuild --version
                      # # export PATH="$PATH:/root/.dotnet/tools"
                      # # export SONAR_SCANNER_OPTS="-Xmx4096m"
                      # sudo apt update
                      # sudo apt install openjdk-17-jdk
                      # sudo update-alternatives --config java
                      # # export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                      # # export PATH="$PATH:$JAVA_HOME/bin"
                      # java --version
                      # dotnet tool install --global dotnet-sonarscanner
                      dotnet pack MyAppT/MyAppT.csproj --configuration '<+stage.variables.Configuration>'
                      dotnet build MyAppT/MyAppT.csproj
                      dotnet sonarscanner end /d:sonar.login=<+secrets.getValue("account.harness-user")>
                      dotnet publish --configuration Release --output ./published
                      zip -r published_artifacts.zip ./published
                      ls -ltr
                      PACKAGE_PATH=$(find output -name "*.nupkg")
                      NEW_PACKAGE_PATH=${PACKAGE_PATH%.nupkg}-release.nupkg
                      mv "$PACKAGE_PATH" "$NEW_PACKAGE_PATH"
                      echo "Package renamed to $NEW_PACKAGE_PATH"
                      temp=$(find . -name '*.zip')
                      zip="published_artifacts.101.zip"
                      mv "$temp" "$zip"
                      ls -ltr
                      # export ZipFileName=$(find . -name '*.zip')
                      export ZipFileName=$zip
                      echo "$ZipFileName"


                      echo "<+stage.variables.test1>"
                      echo "<+stage.variables.test2>"
                      echo "<+stage.variables.test3>"
                      echo "<+stage.variables.test4>"
                    outputVariables:
                      - name: ZipFileName
              - step:
                  type: Sonarqube
                  name: Sonarqube
                  identifier: Sonarqube
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: medium
                    auth:
                      access_token: <+secrets.getValue("account.harness-user")>
                      domain: http://13.53.86.216:9000/
                      ssl: true
                    tool:
                      project_key: harness-demo11
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload
                  identifier: ArtifactoryUpload
                  spec:
                    connectorRef: account.IIS
                    target: generic-local/
                    sourcePath: <+stage.variables.zipName>
        variables:
          - name: zipName
            type: String
            description: ""
            required: false
            value: <+pipeline.stages.Build.spec.execution.steps.Build.output.outputVariables.ZipFileName>
          - name: test1
            type: String
            description: ""
            required: true
            value: <+input>
          - name: test2
            type: String
            description: ""
            required: true
            value: <+input>
          - name: test3
            type: String
            description: ""
            required: true
            value: <+input>
          - name: test4
            type: String
            description: ""
            required: true
            value: <+input>
          - name: Configuration
            type: String
            description: ""
            required: true
            value: <+input>.default(Release).allowedValues(Debug,Release)
