# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tx-Automate-Pipeline

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore MyAppT/MyAppT.csproj
    - name: Build
      run: dotnet build MyAppT/MyAppT.csproj --no-restore
    - name: Test
      run: dotnet test TestingProject/TestingProject.csproj --verbosity normal
